// AUTO-GENERATED by `npm run gen:transport` —— 请勿手改。
//
// Story 15.5 TS 侧事件名清单（27 个）：源 crates/egosync-engine/src/events.rs
// （事件名常量唯一发射源；skill-scope-updated 为前端本地事件不入册）。
// payload 类型维持组件内手写接口现状（15.5 裁量：events.rs 无类型信息）。

/** 引擎事件名全名单（27 个，events.rs 声明序）。 */
export const ENGINE_EVENT_NAMES: readonly string[] = [
  'bigrock:protection',
  'bigrock:reminder',
  'briefing:generated',
  'review:generated',
  'q2:reminder',
  'notification:new',
  'task:classified',
  'skill-registry-updated',
  'llm:stream',
  'message:saved',
  'conversation:created',
  'conversation:deleted',
  'conversation:title-updated',
  'role:proposed',
  'role:delegated',
  'task:tool-action',
  'role:created',
  'role:updated',
  'role:archived',
  'role:restored',
  'role:deleted',
  'task:created',
  'task:updated',
  'task:deleted',
  'task:reordered',
  'notification:read',
  'data:imported',
];

/** 引擎事件名字面量联合类型（编译期收窄用）。 */
export type EngineEventName = (typeof ENGINE_EVENT_NAMES)[number];
