//! AUTO-GENERATED by `cargo run --features gen --bin gen_commands` —— 请勿手改。
//!
//! Story 15.4 工件代码镜像：web-ok 命令 dispatch registry（与
//! `crates/egosync-engine/commands.json` 同源机械导出）。
//! 参数 camelCase 反序列化与桌面 invoke 同构（Option 缺省 → None）；
//! 业务错误一律 `AppError`（路由层 200 + 单键 map）；未知命令 → NotFound。

use egosync_engine::commands::ctx::EngineCtx;
use egosync_engine::error::AppError;

/// web-ok 命令全名单（生成物；对等断言与 commands.json 工件互验）。
pub const WEB_OK_COMMANDS: &[&str] = &[
    "app_complete_onboarding",
    "app_get_butler_skills",
    "app_get_setting",
    "app_is_first_launch",
    "app_is_llm_configured",
    "app_performance_snapshot",
    "app_set_setting",
    "app_sidecar_status",
    "app_update_butler_skills",
    "briefing_generate_now",
    "briefing_get_latest",
    "chat_delete_conversation",
    "chat_get_butler_conversation",
    "chat_get_conversation",
    "chat_get_history",
    "chat_get_message_process_events",
    "chat_get_role_conversation",
    "chat_list_conversations",
    "chat_new_conversation",
    "chat_send_message",
    "chat_stop_streaming",
    "dashboard_get_metrics",
    "dashboard_get_status",
    "data_destroy",
    "llm_config_create",
    "llm_config_delete",
    "llm_config_list",
    "llm_config_list_models",
    "llm_config_list_models_by_params",
    "llm_config_set_default",
    "llm_config_test_connection",
    "llm_config_update",
    "mcp_server_add_to_butler",
    "mcp_server_add_to_role",
    "mcp_server_create",
    "mcp_server_delete",
    "mcp_server_list",
    "mcp_server_list_available_for_butler",
    "mcp_server_list_available_for_role",
    "mcp_server_list_for_butler",
    "mcp_server_list_for_role",
    "mcp_server_refresh_butler_runtime",
    "mcp_server_remove_from_butler",
    "mcp_server_remove_from_role",
    "mcp_server_test",
    "mcp_server_update",
    "memory_count",
    "memory_delete",
    "memory_get_source_messages",
    "memory_list",
    "memory_list_all",
    "mission_get",
    "mission_infer",
    "mission_infer_eligibility",
    "mission_update",
    "notification_count_unread",
    "notification_create",
    "notification_list",
    "notification_mark_read",
    "review_generate_now",
    "review_get_bigrock_suggestions",
    "review_get_by_week",
    "review_get_latest",
    "review_plan_bigrocks",
    "role_archive",
    "role_create",
    "role_delete",
    "role_list",
    "role_list_archived",
    "role_restore",
    "role_update",
    "role_update_proactivity",
    "role_update_skills",
    "scheduler_get_times",
    "scheduler_set_times",
    "secret_store_delete",
    "secret_store_load",
    "secret_store_save",
    "settings_get_schedule",
    "settings_update_schedule",
    "skill_delete",
    "skill_discover_opencode",
    "skill_import_custom",
    "skill_import_opencode",
    "skill_list_all_role_skills",
    "skill_list_for_role",
    "skill_list_registry",
    "skill_list_selectable_for_scope",
    "skill_preview_custom",
    "skill_remove_from_role",
    "suggestion_confirm",
    "suggestion_list_pending",
    "suggestion_reject",
    "task_check_protection_status",
    "task_check_q2_reminders",
    "task_create",
    "task_decomposition_accept",
    "task_decomposition_keep_single",
    "task_decomposition_list_pending",
    "task_delete",
    "task_list_all",
    "task_list_butler",
    "task_list_by_role",
    "task_reorder",
    "task_toggle_complete",
    "task_update",
];

mod params {
    /// `app_get_setting` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PAppGetSetting {
        pub key: String,
    }

    /// `app_set_setting` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PAppSetSetting {
        pub key: String,
        pub value: String,
    }

    /// `app_update_butler_skills` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PAppUpdateButlerSkills {
        pub input: egosync_engine::models::role::UpdateRoleSkillsInput,
    }

    /// `chat_delete_conversation` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatDeleteConversation {
        pub conversation_id: String,
    }

    /// `chat_get_conversation` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatGetConversation {
        pub conversation_id: String,
    }

    /// `chat_get_history` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatGetHistory {
        pub conversation_id: String,
    }

    /// `chat_get_message_process_events` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatGetMessageProcessEvents {
        pub message_id: String,
    }

    /// `chat_get_role_conversation` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatGetRoleConversation {
        pub role_id: String,
    }

    /// `chat_list_conversations` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatListConversations {
        #[serde(default)]
        pub role_id: Option<String>,
    }

    /// `chat_new_conversation` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatNewConversation {
        #[serde(default)]
        pub old_conversation_id: Option<String>,
        #[serde(default)]
        pub role_id: Option<String>,
    }

    /// `chat_send_message` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatSendMessage {
        pub request: egosync_engine::models::chat::ChatRequest,
    }

    /// `chat_stop_streaming` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PChatStopStreaming {
        pub conversation_id: String,
    }

    /// `dashboard_get_metrics` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PDashboardGetMetrics {
        pub query: egosync_engine::models::dashboard::DashboardMetricsQuery,
    }

    /// `llm_config_create` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigCreate {
        pub input: egosync_engine::models::settings::CreateLlmConfigInput,
    }

    /// `llm_config_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigDelete {
        pub id: String,
    }

    /// `llm_config_list_models` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigListModels {
        pub id: String,
    }

    /// `llm_config_list_models_by_params` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigListModelsByParams {
        pub provider: String,
        pub base_url: String,
        pub api_key: String,
        pub network_location: egosync_engine::models::settings::NetworkLocation,
    }

    /// `llm_config_set_default` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigSetDefault {
        pub id: String,
    }

    /// `llm_config_test_connection` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigTestConnection {
        pub id: String,
    }

    /// `llm_config_update` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PLlmConfigUpdate {
        pub id: String,
        pub input: egosync_engine::models::settings::UpdateLlmConfigInput,
    }

    /// `mcp_server_add_to_butler` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerAddToButler {
        pub server_id: String,
    }

    /// `mcp_server_add_to_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerAddToRole {
        pub role_id: String,
        pub server_id: String,
    }

    /// `mcp_server_create` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerCreate {
        pub input: egosync_engine::models::mcp::CreateMcpServerInput,
    }

    /// `mcp_server_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerDelete {
        pub id: String,
    }

    /// `mcp_server_list_available_for_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerListAvailableForRole {
        pub role_id: String,
    }

    /// `mcp_server_list_for_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerListForRole {
        pub role_id: String,
    }

    /// `mcp_server_remove_from_butler` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerRemoveFromButler {
        pub server_id: String,
    }

    /// `mcp_server_remove_from_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerRemoveFromRole {
        pub role_id: String,
        pub server_id: String,
    }

    /// `mcp_server_test` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerTest {
        pub id: String,
    }

    /// `mcp_server_update` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMcpServerUpdate {
        pub id: String,
        pub input: egosync_engine::models::mcp::UpdateMcpServerInput,
    }

    /// `memory_count` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMemoryCount {
        #[serde(default)]
        pub role_id: Option<String>,
        #[serde(default)]
        pub include_role_memories: Option<bool>,
        #[serde(default)]
        pub category: Option<String>,
    }

    /// `memory_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMemoryDelete {
        pub memory_id: String,
    }

    /// `memory_get_source_messages` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMemoryGetSourceMessages {
        pub memory_id: String,
    }

    /// `memory_list` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMemoryList {
        #[serde(default)]
        pub role_id: Option<String>,
        #[serde(default)]
        pub category: Option<String>,
        #[serde(default)]
        pub limit: Option<i64>,
        #[serde(default)]
        pub offset: Option<i64>,
    }

    /// `memory_list_all` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMemoryListAll {
        #[serde(default)]
        pub category: Option<String>,
        #[serde(default)]
        pub limit: Option<i64>,
        #[serde(default)]
        pub offset: Option<i64>,
    }

    /// `mission_update` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PMissionUpdate {
        #[serde(default)]
        pub content: Option<String>,
        pub format: String,
    }

    /// `notification_create` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PNotificationCreate {
        pub input: egosync_engine::models::notification::CreateNotificationInput,
    }

    /// `notification_mark_read` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PNotificationMarkRead {
        pub id: String,
    }

    /// `review_get_by_week` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PReviewGetByWeek {
        pub week_start: String,
    }

    /// `review_plan_bigrocks` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PReviewPlanBigrocks {
        pub items: Vec<egosync_engine::commands::review::BigRockPlanItem>,
    }

    /// `role_archive` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleArchive {
        pub id: String,
    }

    /// `role_create` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleCreate {
        pub input: egosync_engine::models::role::CreateRoleInput,
    }

    /// `role_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleDelete {
        pub id: String,
    }

    /// `role_restore` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleRestore {
        pub id: String,
    }

    /// `role_update` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleUpdate {
        pub id: String,
        pub input: egosync_engine::models::role::UpdateRoleInput,
    }

    /// `role_update_proactivity` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleUpdateProactivity {
        pub id: String,
        pub input: egosync_engine::models::role::UpdateRoleProactivityInput,
    }

    /// `role_update_skills` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PRoleUpdateSkills {
        pub id: String,
        pub input: egosync_engine::models::role::UpdateRoleSkillsInput,
    }

    /// `scheduler_set_times` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSchedulerSetTimes {
        pub moderate: Vec<String>,
        pub proactive: Vec<String>,
    }

    /// `secret_store_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSecretStoreDelete {
        pub key: String,
    }

    /// `secret_store_load` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSecretStoreLoad {
        pub key: String,
    }

    /// `secret_store_save` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSecretStoreSave {
        pub key: String,
        pub value: String,
    }

    /// `settings_update_schedule` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSettingsUpdateSchedule {
        #[serde(default)]
        pub briefing_time: Option<String>,
        #[serde(default)]
        pub review_day: Option<String>,
        #[serde(default)]
        pub review_time: Option<String>,
        #[serde(default)]
        pub bigrock_reminder_day: Option<String>,
        #[serde(default)]
        pub bigrock_reminder_time: Option<String>,
    }

    /// `skill_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillDelete {
        pub skill_id: String,
    }

    /// `skill_discover_opencode` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillDiscoverOpencode {
        pub role_id: String,
    }

    /// `skill_import_custom` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillImportCustom {
        pub input: egosync_engine::models::skill::ImportCustomSkillInput,
    }

    /// `skill_import_opencode` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillImportOpencode {
        pub role_id: String,
        pub input: egosync_engine::models::skill::ImportOpencodeSkillInput,
    }

    /// `skill_list_for_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillListForRole {
        pub role_id: String,
    }

    /// `skill_list_selectable_for_scope` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillListSelectableForScope {
        #[serde(default)]
        pub role_id: Option<String>,
    }

    /// `skill_preview_custom` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillPreviewCustom {
        pub input: egosync_engine::models::skill::PreviewCustomSkillInput,
    }

    /// `skill_remove_from_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSkillRemoveFromRole {
        pub skill_id: String,
        pub role_id: String,
    }

    /// `suggestion_confirm` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSuggestionConfirm {
        pub id: String,
    }

    /// `suggestion_list_pending` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSuggestionListPending {
        pub conversation_id: String,
    }

    /// `suggestion_reject` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PSuggestionReject {
        pub id: String,
        pub reason: String,
    }

    /// `task_create` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskCreate {
        pub input: egosync_engine::models::task::CreateTaskInput,
    }

    /// `task_decomposition_accept` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskDecompositionAccept {
        pub id: String,
    }

    /// `task_decomposition_keep_single` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskDecompositionKeepSingle {
        pub id: String,
    }

    /// `task_decomposition_list_pending` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskDecompositionListPending {
        pub conversation_id: String,
    }

    /// `task_delete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskDelete {
        pub id: String,
    }

    /// `task_list_all` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskListAll {
        #[serde(default)]
        pub quadrant: Option<String>,
        #[serde(default)]
        pub is_big_rock: Option<bool>,
    }

    /// `task_list_by_role` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskListByRole {
        pub role_id: String,
    }

    /// `task_reorder` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskReorder {
        pub task_ids: Vec<String>,
    }

    /// `task_toggle_complete` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskToggleComplete {
        pub task_id: String,
        pub is_completed: bool,
    }

    /// `task_update` 的客户端参数（camelCase 解包，与 invoke 同构）。
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PTaskUpdate {
        pub id: String,
        pub input: egosync_engine::models::task::UpdateTaskInput,
    }

}

/// 解码客户端参数（camelCase body → 命令参数；与 invoke 同构）。
/// 类型不符 ⇒ `ValidationError`（路由层 200 单键 map 形状）。
fn decode<T: serde::de::DeserializeOwned>(params: serde_json::Value) -> Result<T, AppError> {
    serde_json::from_value(params)
        .map_err(|e| AppError::ValidationError(format!("参数反序列化失败: {}", e)))
}

/// 编码命令返回值。
fn encode<T: serde::Serialize>(value: T) -> Result<serde_json::Value, AppError> {
    serde_json::to_value(value)
        .map_err(|e| AppError::ValidationError(format!("返回值序列化失败: {}", e)))
}

/// 命令分发：按名路由至引擎命令体（首参 ctx 注入）。
/// 未知名（含 desktop-only / perf-test 门控）→ `NotFound`（路由层 404）。
pub async fn dispatch(
    ctx: &EngineCtx,
    command: &str,
    params: serde_json::Value,
) -> Result<serde_json::Value, AppError> {
    match command {
        "app_complete_onboarding" => {
        let result = egosync_engine::commands::app::app_complete_onboarding(
            ctx
        ).await?;
        encode(result)
        }
        "app_get_butler_skills" => {
        let result = egosync_engine::commands::app::app_get_butler_skills(
            ctx
        ).await?;
        encode(result)
        }
        "app_get_setting" => {
        let p: params::PAppGetSetting = decode(params)?;
        let result = egosync_engine::commands::app::app_get_setting(
            ctx,
            p.key
        ).await?;
        encode(result)
        }
        "app_is_first_launch" => {
        let result = egosync_engine::commands::app::app_is_first_launch(
            ctx
        ).await?;
        encode(result)
        }
        "app_is_llm_configured" => {
        let result = egosync_engine::commands::app::app_is_llm_configured(
            ctx
        ).await?;
        encode(result)
        }
        "app_performance_snapshot" => {
        let result = egosync_engine::commands::app::app_performance_snapshot(
            ctx
        ).await?;
        encode(result)
        }
        "app_set_setting" => {
        let p: params::PAppSetSetting = decode(params)?;
        let result = egosync_engine::commands::app::app_set_setting(
            ctx,
            p.key,
            p.value
        ).await?;
        encode(result)
        }
        "app_sidecar_status" => {
        let result = egosync_engine::commands::app::app_sidecar_status(
            ctx
        ).await?;
        encode(result)
        }
        "app_update_butler_skills" => {
        let p: params::PAppUpdateButlerSkills = decode(params)?;
        let result = egosync_engine::commands::app::app_update_butler_skills(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "briefing_generate_now" => {
        let result = egosync_engine::commands::briefing::briefing_generate_now(
            ctx
        ).await?;
        encode(result)
        }
        "briefing_get_latest" => {
        let result = egosync_engine::commands::briefing::briefing_get_latest(
            ctx
        ).await?;
        encode(result)
        }
        "chat_delete_conversation" => {
        let p: params::PChatDeleteConversation = decode(params)?;
        let result = egosync_engine::commands::chat::chat_delete_conversation(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "chat_get_butler_conversation" => {
        let result = egosync_engine::commands::chat::chat_get_butler_conversation(
            ctx
        ).await?;
        encode(result)
        }
        "chat_get_conversation" => {
        let p: params::PChatGetConversation = decode(params)?;
        let result = egosync_engine::commands::chat::chat_get_conversation(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "chat_get_history" => {
        let p: params::PChatGetHistory = decode(params)?;
        let result = egosync_engine::commands::chat::chat_get_history(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "chat_get_message_process_events" => {
        let p: params::PChatGetMessageProcessEvents = decode(params)?;
        let result = egosync_engine::commands::chat::chat_get_message_process_events(
            ctx,
            p.message_id
        ).await?;
        encode(result)
        }
        "chat_get_role_conversation" => {
        let p: params::PChatGetRoleConversation = decode(params)?;
        let result = egosync_engine::commands::chat::chat_get_role_conversation(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "chat_list_conversations" => {
        let p: params::PChatListConversations = decode(params)?;
        let result = egosync_engine::commands::chat::chat_list_conversations(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "chat_new_conversation" => {
        let p: params::PChatNewConversation = decode(params)?;
        let result = egosync_engine::commands::chat::chat_new_conversation(
            ctx,
            p.old_conversation_id,
            p.role_id
        ).await?;
        encode(result)
        }
        "chat_send_message" => {
        let p: params::PChatSendMessage = decode(params)?;
        let result = egosync_engine::commands::chat::chat_send_message(
            ctx,
            p.request
        ).await?;
        encode(result)
        }
        "chat_stop_streaming" => {
        let p: params::PChatStopStreaming = decode(params)?;
        let result = egosync_engine::commands::chat::chat_stop_streaming(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "dashboard_get_metrics" => {
        let p: params::PDashboardGetMetrics = decode(params)?;
        let result = egosync_engine::commands::dashboard::dashboard_get_metrics(
            ctx,
            p.query
        ).await?;
        encode(result)
        }
        "dashboard_get_status" => {
        let result = egosync_engine::commands::dashboard::dashboard_get_status(
            ctx
        ).await?;
        encode(result)
        }
        "data_destroy" => {
        let result = egosync_engine::commands::data::data_destroy(
            ctx
        ).await?;
        encode(result)
        }
        "llm_config_create" => {
        let p: params::PLlmConfigCreate = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_create(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "llm_config_delete" => {
        let p: params::PLlmConfigDelete = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_delete(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "llm_config_list" => {
        let result = egosync_engine::commands::llm_config::llm_config_list(
            ctx
        ).await?;
        encode(result)
        }
        "llm_config_list_models" => {
        let p: params::PLlmConfigListModels = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_list_models(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "llm_config_list_models_by_params" => {
        let p: params::PLlmConfigListModelsByParams = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_list_models_by_params(
            p.provider,
            p.base_url,
            p.api_key,
            p.network_location
        ).await?;
        encode(result)
        }
        "llm_config_set_default" => {
        let p: params::PLlmConfigSetDefault = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_set_default(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "llm_config_test_connection" => {
        let p: params::PLlmConfigTestConnection = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_test_connection(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "llm_config_update" => {
        let p: params::PLlmConfigUpdate = decode(params)?;
        let result = egosync_engine::commands::llm_config::llm_config_update(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        "mcp_server_add_to_butler" => {
        let p: params::PMcpServerAddToButler = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_add_to_butler(
            ctx,
            p.server_id
        ).await?;
        encode(result)
        }
        "mcp_server_add_to_role" => {
        let p: params::PMcpServerAddToRole = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_add_to_role(
            ctx,
            p.role_id,
            p.server_id
        ).await?;
        encode(result)
        }
        "mcp_server_create" => {
        let p: params::PMcpServerCreate = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_create(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "mcp_server_delete" => {
        let p: params::PMcpServerDelete = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_delete(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "mcp_server_list" => {
        let result = egosync_engine::commands::mcp::mcp_server_list(
            ctx
        ).await?;
        encode(result)
        }
        "mcp_server_list_available_for_butler" => {
        let result = egosync_engine::commands::mcp::mcp_server_list_available_for_butler(
            ctx
        ).await?;
        encode(result)
        }
        "mcp_server_list_available_for_role" => {
        let p: params::PMcpServerListAvailableForRole = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_list_available_for_role(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "mcp_server_list_for_butler" => {
        let result = egosync_engine::commands::mcp::mcp_server_list_for_butler(
            ctx
        ).await?;
        encode(result)
        }
        "mcp_server_list_for_role" => {
        let p: params::PMcpServerListForRole = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_list_for_role(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "mcp_server_refresh_butler_runtime" => {
        let result = egosync_engine::commands::mcp::mcp_server_refresh_butler_runtime(
            ctx
        ).await?;
        encode(result)
        }
        "mcp_server_remove_from_butler" => {
        let p: params::PMcpServerRemoveFromButler = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_remove_from_butler(
            ctx,
            p.server_id
        ).await?;
        encode(result)
        }
        "mcp_server_remove_from_role" => {
        let p: params::PMcpServerRemoveFromRole = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_remove_from_role(
            ctx,
            p.role_id,
            p.server_id
        ).await?;
        encode(result)
        }
        "mcp_server_test" => {
        let p: params::PMcpServerTest = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_test(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "mcp_server_update" => {
        let p: params::PMcpServerUpdate = decode(params)?;
        let result = egosync_engine::commands::mcp::mcp_server_update(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        "memory_count" => {
        let p: params::PMemoryCount = decode(params)?;
        let result = egosync_engine::commands::memory::memory_count(
            ctx,
            p.role_id,
            p.include_role_memories,
            p.category
        ).await?;
        encode(result)
        }
        "memory_delete" => {
        let p: params::PMemoryDelete = decode(params)?;
        let result = egosync_engine::commands::memory::memory_delete(
            ctx,
            p.memory_id
        ).await?;
        encode(result)
        }
        "memory_get_source_messages" => {
        let p: params::PMemoryGetSourceMessages = decode(params)?;
        let result = egosync_engine::commands::memory::memory_get_source_messages(
            ctx,
            p.memory_id
        ).await?;
        encode(result)
        }
        "memory_list" => {
        let p: params::PMemoryList = decode(params)?;
        let result = egosync_engine::commands::memory::memory_list(
            ctx,
            p.role_id,
            p.category,
            p.limit,
            p.offset
        ).await?;
        encode(result)
        }
        "memory_list_all" => {
        let p: params::PMemoryListAll = decode(params)?;
        let result = egosync_engine::commands::memory::memory_list_all(
            ctx,
            p.category,
            p.limit,
            p.offset
        ).await?;
        encode(result)
        }
        "mission_get" => {
        let result = egosync_engine::commands::mission::mission_get(
            ctx
        ).await?;
        encode(result)
        }
        "mission_infer" => {
        let result = egosync_engine::commands::mission::mission_infer(
            ctx
        ).await?;
        encode(result)
        }
        "mission_infer_eligibility" => {
        let result = egosync_engine::commands::mission::mission_infer_eligibility(
            ctx
        ).await?;
        encode(result)
        }
        "mission_update" => {
        let p: params::PMissionUpdate = decode(params)?;
        let result = egosync_engine::commands::mission::mission_update(
            ctx,
            p.content,
            p.format
        ).await?;
        encode(result)
        }
        "notification_count_unread" => {
        let result = egosync_engine::commands::notification::notification_count_unread(
            ctx
        ).await?;
        encode(result)
        }
        "notification_create" => {
        let p: params::PNotificationCreate = decode(params)?;
        let result = egosync_engine::commands::notification::notification_create(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "notification_list" => {
        let result = egosync_engine::commands::notification::notification_list(
            ctx
        ).await?;
        encode(result)
        }
        "notification_mark_read" => {
        let p: params::PNotificationMarkRead = decode(params)?;
        let result = egosync_engine::commands::notification::notification_mark_read(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "review_generate_now" => {
        let result = egosync_engine::commands::review::review_generate_now(
            ctx
        ).await?;
        encode(result)
        }
        "review_get_bigrock_suggestions" => {
        let result = egosync_engine::commands::review::review_get_bigrock_suggestions(
            ctx
        ).await?;
        encode(result)
        }
        "review_get_by_week" => {
        let p: params::PReviewGetByWeek = decode(params)?;
        let result = egosync_engine::commands::review::review_get_by_week(
            ctx,
            p.week_start
        ).await?;
        encode(result)
        }
        "review_get_latest" => {
        let result = egosync_engine::commands::review::review_get_latest(
            ctx
        ).await?;
        encode(result)
        }
        "review_plan_bigrocks" => {
        let p: params::PReviewPlanBigrocks = decode(params)?;
        let result = egosync_engine::commands::review::review_plan_bigrocks(
            ctx,
            p.items
        ).await?;
        encode(result)
        }
        "role_archive" => {
        let p: params::PRoleArchive = decode(params)?;
        let result = egosync_engine::commands::role::role_archive(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "role_create" => {
        let p: params::PRoleCreate = decode(params)?;
        let result = egosync_engine::commands::role::role_create(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "role_delete" => {
        let p: params::PRoleDelete = decode(params)?;
        let result = egosync_engine::commands::role::role_delete(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "role_list" => {
        let result = egosync_engine::commands::role::role_list(
            ctx
        ).await?;
        encode(result)
        }
        "role_list_archived" => {
        let result = egosync_engine::commands::role::role_list_archived(
            ctx
        ).await?;
        encode(result)
        }
        "role_restore" => {
        let p: params::PRoleRestore = decode(params)?;
        let result = egosync_engine::commands::role::role_restore(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "role_update" => {
        let p: params::PRoleUpdate = decode(params)?;
        let result = egosync_engine::commands::role::role_update(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        "role_update_proactivity" => {
        let p: params::PRoleUpdateProactivity = decode(params)?;
        let result = egosync_engine::commands::role::role_update_proactivity(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        "role_update_skills" => {
        let p: params::PRoleUpdateSkills = decode(params)?;
        let result = egosync_engine::commands::role::role_update_skills(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        "scheduler_get_times" => {
        let result = egosync_engine::commands::scheduler::scheduler_get_times(
            ctx
        ).await?;
        encode(result)
        }
        "scheduler_set_times" => {
        let p: params::PSchedulerSetTimes = decode(params)?;
        let result = egosync_engine::commands::scheduler::scheduler_set_times(
            ctx,
            p.moderate,
            p.proactive
        ).await?;
        encode(result)
        }
        "secret_store_delete" => {
        let p: params::PSecretStoreDelete = decode(params)?;
        let result = egosync_engine::commands::secret::secret_store_delete(
            ctx,
            p.key
        ).await?;
        encode(result)
        }
        "secret_store_load" => {
        let p: params::PSecretStoreLoad = decode(params)?;
        let result = egosync_engine::commands::secret::secret_store_load(
            ctx,
            p.key
        ).await?;
        encode(result)
        }
        "secret_store_save" => {
        let p: params::PSecretStoreSave = decode(params)?;
        let result = egosync_engine::commands::secret::secret_store_save(
            ctx,
            p.key,
            p.value
        ).await?;
        encode(result)
        }
        "settings_get_schedule" => {
        let result = egosync_engine::commands::settings::settings_get_schedule(
            ctx
        ).await?;
        encode(result)
        }
        "settings_update_schedule" => {
        let p: params::PSettingsUpdateSchedule = decode(params)?;
        let result = egosync_engine::commands::settings::settings_update_schedule(
            ctx,
            p.briefing_time,
            p.review_day,
            p.review_time,
            p.bigrock_reminder_day,
            p.bigrock_reminder_time
        ).await?;
        encode(result)
        }
        "skill_delete" => {
        let p: params::PSkillDelete = decode(params)?;
        let result = egosync_engine::commands::skill::skill_delete(
            ctx,
            p.skill_id
        ).await?;
        encode(result)
        }
        "skill_discover_opencode" => {
        let p: params::PSkillDiscoverOpencode = decode(params)?;
        let result = egosync_engine::commands::skill::skill_discover_opencode(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "skill_import_custom" => {
        let p: params::PSkillImportCustom = decode(params)?;
        let result = egosync_engine::commands::skill::skill_import_custom(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "skill_import_opencode" => {
        let p: params::PSkillImportOpencode = decode(params)?;
        let result = egosync_engine::commands::skill::skill_import_opencode(
            ctx,
            p.role_id,
            p.input
        ).await?;
        encode(result)
        }
        "skill_list_all_role_skills" => {
        let result = egosync_engine::commands::skill::skill_list_all_role_skills(
            ctx
        ).await?;
        encode(result)
        }
        "skill_list_for_role" => {
        let p: params::PSkillListForRole = decode(params)?;
        let result = egosync_engine::commands::skill::skill_list_for_role(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "skill_list_registry" => {
        let result = egosync_engine::commands::skill::skill_list_registry(
            ctx
        ).await?;
        encode(result)
        }
        "skill_list_selectable_for_scope" => {
        let p: params::PSkillListSelectableForScope = decode(params)?;
        let result = egosync_engine::commands::skill::skill_list_selectable_for_scope(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "skill_preview_custom" => {
        let p: params::PSkillPreviewCustom = decode(params)?;
        let result = egosync_engine::commands::skill::skill_preview_custom(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "skill_remove_from_role" => {
        let p: params::PSkillRemoveFromRole = decode(params)?;
        let result = egosync_engine::commands::skill::skill_remove_from_role(
            ctx,
            p.skill_id,
            p.role_id
        ).await?;
        encode(result)
        }
        "suggestion_confirm" => {
        let p: params::PSuggestionConfirm = decode(params)?;
        let result = egosync_engine::commands::suggestion::suggestion_confirm(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "suggestion_list_pending" => {
        let p: params::PSuggestionListPending = decode(params)?;
        let result = egosync_engine::commands::suggestion::suggestion_list_pending(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "suggestion_reject" => {
        let p: params::PSuggestionReject = decode(params)?;
        let result = egosync_engine::commands::suggestion::suggestion_reject(
            ctx,
            p.id,
            p.reason
        ).await?;
        encode(result)
        }
        "task_check_protection_status" => {
        let result = egosync_engine::commands::task::task_check_protection_status(
            ctx
        ).await?;
        encode(result)
        }
        "task_check_q2_reminders" => {
        let result = egosync_engine::commands::task::task_check_q2_reminders(
            ctx
        ).await?;
        encode(result)
        }
        "task_create" => {
        let p: params::PTaskCreate = decode(params)?;
        let result = egosync_engine::commands::task::task_create(
            ctx,
            p.input
        ).await?;
        encode(result)
        }
        "task_decomposition_accept" => {
        let p: params::PTaskDecompositionAccept = decode(params)?;
        let result = egosync_engine::commands::task_decomposition::task_decomposition_accept(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "task_decomposition_keep_single" => {
        let p: params::PTaskDecompositionKeepSingle = decode(params)?;
        let result = egosync_engine::commands::task_decomposition::task_decomposition_keep_single(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "task_decomposition_list_pending" => {
        let p: params::PTaskDecompositionListPending = decode(params)?;
        let result = egosync_engine::commands::task_decomposition::task_decomposition_list_pending(
            ctx,
            p.conversation_id
        ).await?;
        encode(result)
        }
        "task_delete" => {
        let p: params::PTaskDelete = decode(params)?;
        let result = egosync_engine::commands::task::task_delete(
            ctx,
            p.id
        ).await?;
        encode(result)
        }
        "task_list_all" => {
        let p: params::PTaskListAll = decode(params)?;
        let result = egosync_engine::commands::task::task_list_all(
            ctx,
            p.quadrant,
            p.is_big_rock
        ).await?;
        encode(result)
        }
        "task_list_butler" => {
        let result = egosync_engine::commands::task::task_list_butler(
            ctx
        ).await?;
        encode(result)
        }
        "task_list_by_role" => {
        let p: params::PTaskListByRole = decode(params)?;
        let result = egosync_engine::commands::task::task_list_by_role(
            ctx,
            p.role_id
        ).await?;
        encode(result)
        }
        "task_reorder" => {
        let p: params::PTaskReorder = decode(params)?;
        let result = egosync_engine::commands::task::task_reorder(
            ctx,
            p.task_ids
        ).await?;
        encode(result)
        }
        "task_toggle_complete" => {
        let p: params::PTaskToggleComplete = decode(params)?;
        let result = egosync_engine::commands::task::task_toggle_complete(
            ctx,
            p.task_id,
            p.is_completed
        ).await?;
        encode(result)
        }
        "task_update" => {
        let p: params::PTaskUpdate = decode(params)?;
        let result = egosync_engine::commands::task::task_update(
            ctx,
            p.id,
            p.input
        ).await?;
        encode(result)
        }
        _ => Err(AppError::NotFound(format!("未知命令: {}", command))),
    }
}
